# Generated by Django 2.2.7 on 2019-12-16 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algo_explained', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='catagories',
            new_name='categories',
        ),
    ]
